### ISSUE TITLE
Work with Acrobat Reader

### ISSUE THREAD

**Issue by reejbee** [beatngu13/pdf-zoom-wizard#15]
Hi, Can you tell me if this works with Acrobat Reader DC? 
 I tried to install and run and it is failing, but I think this might be why. 

 Thanks, 
- Rena

**Comment by beatngu13** [comment]
Hey Rena,

it is a standalone application, so there is no need for compatibility with Acrobat. Have you had a look at the [wiki](https://github.com/beatngu13/pdf-zoom-wizard/wiki/) for the getting started guide?

And when you say it is failing, what is the error you get?

Regards,
Daniel

**Comment by reejbee** [comment]
Hi Daniel, 
The State: status is "FAILED" and nothing happens to my *.pdf file. 

 - Rena

**Comment by beatngu13** [comment]
Would mind attaching the PDF so that I can reproduce the error locally?

**Comment by reejbee** [comment]
[report_blank.pdf](https://github.com/beatngu13/pdf-zoom-wizard/files/2171402/report_blank.pdf)

**Comment by beatngu13** [comment]
Thank you for the PDF, I was able to reproduce the error. I assume it is LaTeX-based report? I had similar issues in the past.

However, it seems to be a bug in the PDF library I'm currently using. Since this library isn't active anymore (no updates since 2013), I was planning to switch to another one—but this will take a while.

I will keep this issue open, then you get notified as soon as I'm able to come up with a fix.

**Comment by beatngu13** [comment]
Duplicate of #17.
