### ISSUE TITLE
Version is null

### ISSUE THREAD

**Issue by beatngu13** [beatngu13/pdf-zoom-wizard#278]
### Expected Behavior

The PDF Zoom Wizard Version should be logged.

### Actual Behavior

The version is `null`:

```text
14:43:50.062 [JavaFX Application Thread] INFO  Launcher - Launching PDF Zoom Wizard vnull.
```

I assume this is because the implementation version is only set for the fat JAR, not for the native image:

https://github.com/beatngu13/pdf-zoom-wizard/blob/develop/pom.xml#L167

The actual issue seems to be resolved:

[#2228](https://github.com/oracle/graal/issues/2228)

However, configuration is not clear.

### Steps to Reproduce

1. Launch the PDF Zoom Wizard (native image)
2. Check out the log (file)

### Log

n/a

### Environment

- OS: macOS 11.5.2 (Big Sur)
- PDF Zoom Wizard version: 0.10.0

**Comment by jperedadnr** [comment]
I've done a quick test I've added `pdfclown` dependency to the pom:
```
<dependency>
    <groupId>org.pdfclown</groupId>
    <artifactId>pdfclown</artifactId>
    <version>0.1.2</version>
    <scope>system</scope>
    <systemPath>/tmp/pdf-zoom-wizard-develop/deps/org/pdfclown/pdfclown/0.1.2/pdfclown.jar</systemPath>
</dependency>
```
So now `mvn javafx:run` works fine, but it prints null.
The reason for this: no manifest in the classpath, and classes are not packed in a jar.

Second test:
I've modified your log to printout the pdfclown version instead:
```
logger.info("Launching PDF Zoom Wizard v{}.", org.pdfclown.Engine.class.getPackage().getImplementationVersion());
```
And that works:
```
mvn javafx:run
[INFO] --- javafx-maven-plugin:0.0.8:run (default-cli) @ pdfzoomwizard ---
21:16:10.039 [JavaFX Application Thread] INFO  Launcher - Launching PDF Zoom Wizard v0.1.2.
```
because the pdfclown.jar is a dependency of packed classes with a manifest.
And doing `mvn gluonfx:build gluonfx:nativerun` also works:
```
[INFO] --- gluonfx-maven-plugin:1.0.10:nativerun (default-cli) @ pdfzoomwizard ---
[Mon Dec 20 21:29:16 CET 2021][INFO] ==================== RUN TASK ====================
[Mon Dec 20 21:29:16 CET 2021][INFO] [SUB] 2021-12-20 21:29:16.810 PDF Zoom Wizard[23068:414510] Starting Gluon VM...
[Mon Dec 20 21:29:16 CET 2021][INFO] [SUB] Dec 20, 2021 9:29:16 PM com.sun.javafx.application.PlatformImpl startup
[Mon Dec 20 21:29:16 CET 2021][INFO] [SUB] WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @21c815e4'
[Mon Dec 20 21:29:16 CET 2021][INFO] [SUB] 21:29:16.941 [JavaFX Application Thread] INFO  Launcher - Launching PDF Zoom Wizard v0.1.2.
```

So at this point I see three options:
- Move your core code to a module, publish a jar, and add it to your main project as a dependency, that should work.
- Move your manifest key-values to a properties file, and use the resources plugin. That should work out of the box with the GluonFX plugin (make sure you add the properties extension to the resources List).
- File an [issue](https://github.com/gluonhq/substrate) on Substrate to ask for a manifest. 
So far, Substrate creates a jar out of the project [classes](https://github.com/gluonhq/substrate/blob/master/src/main/java/com/gluonhq/substrate/model/ClassPath.java#L176), so in theory it could also have a manifest, and it could be filed with some key-values coming from the plugin's configuration. Adding the manifest is easy, the problem is adding the changes to the configuration to pass down the key-values.
